/**
 * 全量侧边栏菜单配置
 */
const MENU_CONFIG = [
  { id: 'dashboard', icon: '📊', label: '首页', page: 'dashboard' },
  {
    group: '一期·功能清单',
    icon: '📋',
    children: [
      { id: 'p1-overview', label: '62项功能总览', page: 'p1-overview' },
      { id: 'dash-purchase', label: '采购看板', page: 'dash-purchase' },
      { id: 'dash-ops', label: '运营看板', page: 'dash-ops' },
    ],
  },
  {
    group: 'M1 采购对账',
    icon: '🧾',
    children: [
      { id: 'pur-supplier', label: '供应商档案', page: 'pur-supplier' },
      { id: 'm1-contract', label: '合同管理', page: 'm1-contract' },
      { id: 'm1-rebate-rule', label: '返利规则', page: 'm1-rebate-rule' },
      { id: 'm1-po-approve', label: '采购审批', page: 'm1-po-approve' },
      { id: 'm1-inbound-reg', label: '入库登记', page: 'm1-inbound-reg' },
      { id: 'm1-invoice', label: '发票登记', page: 'm1-invoice' },
      { id: 'm1-three-match', label: '三单比对', page: 'm1-three-match' },
      { id: 'm1-statement', label: '对账单', page: 'm1-statement' },
      { id: 'm1-supplier-portal', label: '供应商确认', page: 'm1-supplier-portal' },
      { id: 'm1-rebate-ledger', label: '返利台账', page: 'm1-rebate-ledger' },
    ],
  },
  {
    group: 'M2 门店补货',
    icon: '📦',
    children: [
      { id: 'sto-list', label: '门店档案', page: 'sto-list' },
      { id: 'm2-sales-data', label: '销售数据', page: 'm2-sales-data' },
      { id: 'm2-replen-config', label: '补货引擎', page: 'm2-replen-config' },
      { id: 'm2-suggestion', label: '补货建议', page: 'm2-suggestion' },
      { id: 'm2-supplier-priority', label: '供应商优先级', page: 'm2-supplier-priority' },
    ],
  },
  {
    group: 'M3 平台商品库存',
    icon: '🔗',
    children: [
      { id: 'prd-spu', label: 'SPU 管理', page: 'prd-spu' },
      { id: 'prd-sku', label: 'SKU 主数据', page: 'prd-sku' },
      { id: 'm3-platform-price', label: '平台定价', page: 'm3-platform-price' },
      { id: 'm3-platform-shelf', label: '平台上下架', page: 'm3-platform-shelf' },
      { id: 'chn-product-map', label: '平台映射', page: 'chn-product-map' },
      { id: 'm3-inv-center', label: '真实库存', page: 'm3-inv-center' },
      { id: 'm3-inv-sync-config', label: '库存同步配置', page: 'm3-inv-sync-config' },
      { id: 'm3-inv-platform-diff', label: '平台库存对账', page: 'm3-inv-platform-diff' },
      { id: 'inv-log', label: '库存流水', page: 'inv-log' },
      { id: 'inv-check', label: '库存盘点', page: 'inv-check' },
      { id: 'ord-channel-pool', label: '订单回传', page: 'ord-channel-pool' },
      { id: 'ord-workflow', label: '履约流程', page: 'ord-workflow' },
      { id: 'chn-sync', label: '同步任务', page: 'chn-sync' },
    ],
  },
  {
    group: 'M4 基础平台',
    icon: '⚙️',
    children: [
      { id: 'sys-dept', label: '组织架构', page: 'sys-dept' },
      { id: 'sys-role', label: '角色权限', page: 'sys-role' },
      { id: 'm4-data-perm', label: '数据权限', page: 'm4-data-perm' },
      { id: 'sys-oper-log', label: '操作日志', page: 'sys-oper-log' },
      { id: 'm4-notify', label: '消息通知', page: 'm4-notify' },
      { id: 'sys-config', label: '系统参数', page: 'sys-config' },
      { id: 'm4-backup', label: '数据备份', page: 'm4-backup' },
      { id: 'sys-user', label: '用户管理', page: 'sys-user' },
    ],
  },
  {
    group: '订单履约',
    icon: '🛒',
    children: [
      { id: 'ord-wave-strategy', label: '波次策略', page: 'ord-wave-strategy' },
      { id: 'ord-wave', label: '波次管理', page: 'ord-wave' },
      { id: 'ord-pick-ship', label: '拣货出库', page: 'ord-pick-ship' },
      { id: 'ord-ship-addr', label: '发货地址', page: 'ord-ship-addr' },
      { id: 'ord-list', label: '订单列表', page: 'ord-list' },
      { id: 'ord-merge', label: '合单管理', page: 'ord-merge' },
      { id: 'ord-after-sale', label: '售后管理', page: 'ord-after-sale' },
    ],
  },
  {
    group: '二期·扩展功能',
    icon: '📁',
    children: [
      { id: 'sys-menu', label: '菜单管理', page: 'sys-menu' },
      { id: 'sys-dict', label: '字典管理', page: 'sys-dict' },
      { id: 'sys-login-log', label: '登录日志', page: 'sys-login-log' },
      { id: 'prd-category', label: '分类管理', page: 'prd-category' },
      { id: 'prd-brand', label: '品牌管理', page: 'prd-brand' },
      { id: 'inv-stock', label: '库存查询', page: 'inv-stock' },
      { id: 'inv-transfer', label: '调拨管理', page: 'inv-transfer' },
      { id: 'inv-inbound', label: '入库管理', page: 'inv-inbound' },
      { id: 'inv-expiry', label: '效期预警', page: 'inv-expiry' },
      { id: 'sto-delivery', label: '配送范围', page: 'sto-delivery' },
      { id: 'chn-config', label: '渠道配置', page: 'chn-config' },
      { id: 'chn-store-map', label: '门店映射', page: 'chn-store-map' },
      { id: 'chn-sync-log', label: '同步日志', page: 'chn-sync-log' },
      { id: 'mem-list', label: '会员列表', page: 'mem-list' },
      { id: 'mem-level', label: '等级管理', page: 'mem-level' },
      { id: 'mem-point', label: '积分管理', page: 'mem-point' },
      { id: 'mem-coupon', label: '优惠券', page: 'mem-coupon' },
      { id: 'pur-order', label: '采购单(旧)', page: 'pur-order' },
      { id: 'pur-return', label: '采购退货', page: 'pur-return' },
      { id: 'fin-bill', label: '平台账单', page: 'fin-bill' },
      { id: 'fin-reconcile', label: '订单对账', page: 'fin-reconcile' },
      { id: 'fin-settlement', label: '门店结算', page: 'fin-settlement' },
      { id: 'rx-pending', label: '待审核处方', page: 'rx-pending' },
      { id: 'rx-list', label: '处方记录', page: 'rx-list' },
      { id: 'rx-log', label: '审核日志', page: 'rx-log' },
      { id: 'del-list', label: '配送单', page: 'del-list' },
      { id: 'del-track', label: '配送跟踪', page: 'del-track' },
      { id: 'rpt-sales', label: '销售报表', page: 'rpt-sales' },
      { id: 'rpt-stock', label: '库存报表', page: 'rpt-stock' },
      { id: 'rpt-purchase', label: '采购报表', page: 'rpt-purchase' },
      { id: 'rpt-analysis', label: '经营分析', page: 'rpt-analysis' },
    ],
  },
];
