/**
 * 一期合同功能页面配置（M1–M4，62 项）
 * 合并至全局 PAGES
 */
const PHASE1_PAGES = {
  'p1-overview': {
    type: 'phase1-overview',
    breadcrumb: '一期建设 / 功能清单总览',
  },
  'dash-purchase': {
    type: 'phase1-dashboard',
    dashboardKind: 'purchase',
    breadcrumb: '一期建设 / 采购看板',
  },
  'dash-ops': {
    type: 'phase1-dashboard',
    dashboardKind: 'ops',
    breadcrumb: '一期建设 / 运营看板',
  },

  /* ===== M1 采购对账自动化 ===== */
  'm1-contract': {
    type: 'list', featureCode: 'M1-1',
    breadcrumb: 'M1 采购对账 / 供应商合同',
    search: [{ label: '供应商', width: 160 }, { label: '状态', type: 'select', options: ['全部', '生效中', '即将到期', '已过期'] }],
    toolbar: ['+ 新增合同', '导出'],
    columns: ['合同编号', '供应商', '有效期至', '账期(天)', '结算方式', '续签提醒', '状态', '操作'],
    total: 0,
  },
  'm1-rebate-rule': {
    type: 'list', featureCode: 'M1-1-4',
    breadcrumb: 'M1 采购对账 / 返利规则',
    toolbar: ['+ 新增规则'],
    columns: ['规则名称', '返利类型', '参数说明', '周期', '状态', '操作'],
    total: 0,
  },
  'm1-po-approve': {
    type: 'list', featureCode: 'M1-2',
    breadcrumb: 'M1 采购对账 / 采购审批',
    search: [{ label: '采购单号', width: 160 }, { label: '审批状态', type: 'select', options: ['全部', '待审批', '已通过', '已驳回'] }],
    toolbar: ['+ 新建采购单', 'Excel 导入'],
    columns: ['采购单号', '供应商', '金额', '审批级别', '合同快照', '状态', '采购员', '操作'],
    total: 0,
  },
  'm1-inbound-reg': {
    type: 'list', featureCode: 'M1-2-3',
    breadcrumb: 'M1 采购对账 / 采购入库登记',
    search: [{ label: '采购单号', width: 160 }, { label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }],
    toolbar: ['+ 入库登记'],
    columns: ['入库单号', '采购单号', 'SKU', '订购数', '实收数', '批号', '有效期', '差异', '操作'],
    total: 0,
  },
  'm1-invoice': {
    type: 'list', featureCode: 'M1-2-5',
    breadcrumb: 'M1 采购对账 / 发票登记',
    search: [{ label: '发票号码', width: 160 }, { label: '供应商', width: 140 }],
    toolbar: ['+ 登记发票', '上传 PDF'],
    columns: ['发票号码', '供应商', '关联采购单', '票面金额', '税率', '登记时间', '操作'],
    total: 0,
  },
  'm1-three-match': {
    type: 'list', featureCode: 'M1-3-1',
    breadcrumb: 'M1 采购对账 / 三单比对',
    search: [{ label: '采购单号', width: 160 }, { label: '差异级别', type: 'select', options: ['全部', '绿', '黄', '红'] }],
    toolbar: ['自动比对', '导出差异'],
    columns: ['采购单号', '应付金额', '入库金额', '发票金额', '差异', '级别', '处理状态', '操作'],
    total: 0,
  },
  'm1-statement': {
    type: 'list', featureCode: 'M1-3-2',
    breadcrumb: 'M1 采购对账 / 对账单',
    search: [{ label: '供应商', width: 140 }, { label: '状态', type: 'select', options: ['全部', '待确认', '已确认', '有差异'] }],
    toolbar: ['生成对账单', '推送供应商'],
    columns: ['对账单号', '供应商', '结算周期', '订单数', '应付总额', '差异级别', '供应商确认', '操作'],
    total: 0,
  },
  'm1-supplier-portal': {
    type: 'list', featureCode: 'M1-4',
    breadcrumb: 'M1 采购对账 / 供应商确认',
    search: [{ label: '供应商', width: 140 }, { label: '确认状态', type: 'select', options: ['全部', '待确认', '已确认', '有异议'] }],
    toolbar: ['批量推送'],
    columns: ['对账单号', '供应商', '应付金额', '推送渠道', '确认状态', '反馈说明', '操作'],
    total: 0,
  },
  'm1-rebate-ledger': {
    type: 'list', featureCode: 'M1-5',
    breadcrumb: 'M1 采购对账 / 返利台账',
    search: [{ label: '供应商', width: 140 }, { label: '预警', type: 'select', options: ['全部', '正常', '预警'] }],
    toolbar: ['计算应返', '登记实返'],
    columns: ['台账编号', '供应商', '规则', '应返金额', '实返金额', '差额', '到期日', '预警', '操作'],
    total: 0,
  },

  /* ===== M2 门店补货 ===== */
  'm2-sales-data': {
    type: 'list', featureCode: 'M2-1-2',
    breadcrumb: 'M2 门店补货 / 销售数据',
    search: [{ label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }, { label: 'SKU', width: 160 }, { label: '日期', width: 120 }],
    toolbar: ['拉取三平台销量', '导出'],
    columns: ['日期', '门店', 'SKU', '商品名', '销量', '渠道', '更新时间'],
    total: 0,
  },
  'm2-replen-config': {
    type: 'form-cards', featureCode: 'M2-2',
    breadcrumb: 'M2 门店补货 / 补货引擎参数',
    cards: [
      { title: '销量预测权重 (M2-2-1)', fields: [{ label: '近7日权重', value: '0.5' }, { label: '近30日权重', value: '0.3' }, { label: '同比上月权重', value: '0.2' }] },
      { title: '安全库存 (M2-2-2)', fields: [{ label: '服务水平', value: '95%' }, { label: '补货提前期(天)', value: '2' }, { label: '波动系数', value: '1.2' }] },
      { title: '供应商匹配 (M2-3)', fields: [{ label: '价格权重', value: '40%' }, { label: '账期权重', value: '20%' }, { label: '时效权重', value: '25%' }, { label: '优先级权重', value: '15%' }] },
    ],
  },
  'm2-suggestion': {
    type: 'list', featureCode: 'M2-2-3',
    breadcrumb: 'M2 门店补货 / 补货建议单',
    search: [{ label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }, { label: '状态', type: 'select', options: ['全部', '待审核', '已通过', '已转采购'] }],
    toolbar: ['生成今日建议', '批量审核', '一键转采购'],
    columns: ['建议单号', '门店', 'SKU', '建议数量', '建议供应商', '预计到货', '匹配得分', '状态', '操作'],
    total: 0,
  },
  'm2-supplier-priority': {
    type: 'list', featureCode: 'M2-3-1',
    breadcrumb: 'M2 门店补货 / 供应商优先级',
    search: [{ label: 'SKU', width: 160 }],
    toolbar: ['+ 配置优先级', '备选切换规则'],
    columns: ['SKU', '商品名', '主供应商', '备选供应商', '账期', '配送时效', '优先级', '操作'],
    total: 0,
  },

  /* ===== M3 三平台商品库存 ===== */
  'm3-platform-price': {
    type: 'list', featureCode: 'M3-2-3',
    breadcrumb: 'M3 平台同步 / 平台独立定价',
    search: [{ label: 'SKU', width: 160 }, { label: '渠道', type: 'select', options: ['全部', '美团', '饿了么', '京东'] }],
    toolbar: ['批量改价', '导出'],
    columns: ['SKU', '商品名', '中台价', '美团价', '饿了么价', '京东价', '最后更新', '操作'],
    total: 0,
  },
  'm3-platform-shelf': {
    type: 'list', featureCode: 'M3-2-4',
    breadcrumb: 'M3 平台同步 / 平台上下架',
    search: [{ label: 'SKU', width: 160 }, { label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }, { label: '渠道', type: 'select', options: ['全部', '美团', '饿了么', '京东'] }],
    toolbar: ['一键同步三平台', '批量上架', '批量下架'],
    columns: ['SKU', '门店', '渠道', '平台状态', '同步状态', '最后同步', '操作'],
    total: 0,
  },
  'm3-inv-center': {
    type: 'list', featureCode: 'M3-3-1',
    breadcrumb: 'M3 平台同步 / 真实库存视图',
    search: [{ label: 'SKU/商品', width: 160 }, { label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }],
    toolbar: ['导出', '库存对账'],
    columns: ['门店', 'SKU', '商品名', '可用', '预占', '在途', '平台推送库存', '冗余比例', '操作'],
    total: 0,
  },
  'm3-inv-sync-config': {
    type: 'form-cards', featureCode: 'M3-3-2',
    breadcrumb: 'M3 平台同步 / 库存同步配置',
    cards: [
      { title: '同步策略', fields: [{ label: '同步延迟上限', value: '30 秒' }, { label: '安全冗余比例', value: '5%' }, { label: '串行扣减', value: tag('已启用', 'on') }] },
      { title: '定时对账 (M3-4-4)', fields: [{ label: '对账频率', value: '每 30 分钟' }, { label: '自动修正', value: '是' }, { label: '上次对账', value: '2026-05-28 11:30' }] },
    ],
  },
  'm3-inv-platform-diff': {
    type: 'list', featureCode: 'M3-4-4',
    breadcrumb: 'M3 平台同步 / 平台库存对账',
    search: [{ label: '门店', type: 'select', options: ['全部门店', '朝阳店', '海淀店'] }, { label: '渠道', type: 'select', options: ['全部', '美团', '饿了么', '京东'] }],
    toolbar: ['立即对账', '自动修正'],
    columns: ['对账时间', '门店', 'SKU', '渠道', '系统库存', '平台库存', '差异', '处理', '操作'],
    total: 0,
  },

  /* ===== M4 基础平台 ===== */
  'm4-data-perm': {
    type: 'list', featureCode: 'M4-3',
    breadcrumb: 'M4 基础平台 / 数据权限',
    toolbar: ['+ 新增规则'],
    columns: ['规则名称', '维度', '范围', '适用角色', '状态', '操作'],
    total: 0,
  },
  'm4-notify': {
    type: 'list', featureCode: 'M4-5',
    breadcrumb: 'M4 基础平台 / 消息通知',
    search: [{ label: '通道', type: 'select', options: ['全部', '短信', '邮件', '企业微信'] }],
    toolbar: ['+ 新增模板', '发送记录'],
    columns: ['模板名称', '业务场景', '通道', '最近发送', '状态', '操作'],
    total: 0,
  },
  'm4-backup': {
    type: 'list', featureCode: 'M4-10',
    breadcrumb: 'M4 基础平台 / 数据备份',
    toolbar: ['立即备份', '恢复向导'],
    columns: ['备份编号', '备份时间', '大小', '保留天数', '状态', '操作'],
    total: 0,
  },
};

/** 62 项功能索引 — 用于总览页 */
const PHASE1_FEATURES = [
  { code: 'M1-1-1', name: '供应商档案管理', page: 'pur-supplier', module: 'M1' },
  { code: 'M1-1-2', name: '合同管理', page: 'm1-contract', module: 'M1' },
  { code: 'M1-1-3', name: '合同条款快照', page: 'm1-po-approve', module: 'M1' },
  { code: 'M1-1-4', name: '返利规则配置', page: 'm1-rebate-rule', module: 'M1' },
  { code: 'M1-2-1', name: '采购订单创建', page: 'm1-po-approve', module: 'M1' },
  { code: 'M1-2-2', name: '采购订单审批', page: 'm1-po-approve', module: 'M1' },
  { code: 'M1-2-3', name: '入库登记', page: 'm1-inbound-reg', module: 'M1' },
  { code: 'M1-2-4', name: '入库与订单关联', page: 'm1-inbound-reg', module: 'M1' },
  { code: 'M1-2-5', name: '发票登记', page: 'm1-invoice', module: 'M1' },
  { code: 'M1-3-1', name: '三单自动比对', page: 'm1-three-match', module: 'M1' },
  { code: 'M1-3-2', name: '对账单自动生成', page: 'm1-statement', module: 'M1' },
  { code: 'M1-3-3', name: '差异分级处理', page: 'm1-three-match', module: 'M1' },
  { code: 'M1-3-4', name: '对账单推送', page: 'm1-statement', module: 'M1' },
  { code: 'M1-4-1', name: '供应商在线登录', page: 'm1-supplier-portal', module: 'M1' },
  { code: 'M1-4-2', name: '在线查看对账单', page: 'm1-supplier-portal', module: 'M1' },
  { code: 'M1-4-3', name: '在线确认与差异反馈', page: 'm1-supplier-portal', module: 'M1' },
  { code: 'M1-5-1', name: '应返自动计算', page: 'm1-rebate-ledger', module: 'M1' },
  { code: 'M1-5-2', name: '实返登记与对比', page: 'm1-rebate-ledger', module: 'M1' },
  { code: 'M1-5-3', name: '返利预警', page: 'm1-rebate-ledger', module: 'M1' },
  { code: 'M2-1-1', name: '门店档案管理', page: 'sto-list', module: 'M2' },
  { code: 'M2-1-2', name: '销售数据自动归集', page: 'm2-sales-data', module: 'M2' },
  { code: 'M2-1-3', name: '实时库存数据归集', page: 'm3-inv-center', module: 'M2' },
  { code: 'M2-2-1', name: '销量预测计算', page: 'm2-replen-config', module: 'M2' },
  { code: 'M2-2-2', name: '安全库存计算', page: 'm2-replen-config', module: 'M2' },
  { code: 'M2-2-3', name: '补货建议生成', page: 'm2-suggestion', module: 'M2' },
  { code: 'M2-2-4', name: '建议单审核', page: 'm2-suggestion', module: 'M2' },
  { code: 'M2-3-1', name: '多供应商优先级', page: 'm2-supplier-priority', module: 'M2' },
  { code: 'M2-3-2', name: '自动选择最优供应商', page: 'm2-suggestion', module: 'M2' },
  { code: 'M2-3-3', name: '备选切换', page: 'm2-supplier-priority', module: 'M2' },
  { code: 'M2-4-1', name: '自动拆单', page: 'm2-suggestion', module: 'M2' },
  { code: 'M2-4-2', name: '自动套用合同', page: 'm2-suggestion', module: 'M2' },
  { code: 'M3-1-1', name: '商品主数据维护', page: 'prd-sku', module: 'M3' },
  { code: 'M3-1-2', name: '医药字段强校验', page: 'prd-sku', module: 'M3' },
  { code: 'M3-1-3', name: '批量导入', page: 'prd-sku', module: 'M3' },
  { code: 'M3-1-4', name: '商品分级管理', page: 'prd-spu', module: 'M3' },
  { code: 'M3-2-1', name: '一键同步三平台', page: 'm3-platform-shelf', module: 'M3' },
  { code: 'M3-2-2', name: '同步状态实时查看', page: 'chn-sync', module: 'M3' },
  { code: 'M3-2-3', name: '平台独立定价', page: 'm3-platform-price', module: 'M3' },
  { code: 'M3-2-4', name: '平台独立上下架', page: 'm3-platform-shelf', module: 'M3' },
  { code: 'M3-2-5', name: '平台映射管理', page: 'chn-product-map', module: 'M3' },
  { code: 'M3-3-1', name: '真实库存视图', page: 'm3-inv-center', module: 'M3' },
  { code: 'M3-3-2', name: '三平台库存实时同步', page: 'm3-inv-sync-config', module: 'M3' },
  { code: 'M3-3-3', name: '库存安全冗余', page: 'm3-inv-sync-config', module: 'M3' },
  { code: 'M3-3-4', name: '库存流水台账', page: 'inv-log', module: 'M3' },
  { code: 'M3-3-5', name: '库存盘点', page: 'inv-check', module: 'M3' },
  { code: 'M3-4-1', name: '平台订单自动回传', page: 'ord-channel-pool', module: 'M3' },
  { code: 'M3-4-2', name: '自动扣减库存', page: 'ord-workflow', module: 'M3' },
  { code: 'M3-4-3', name: '防超卖串行扣减', page: 'm3-inv-sync-config', module: 'M3' },
  { code: 'M3-4-4', name: '库存差异定时对账', page: 'm3-inv-platform-diff', module: 'M3' },
  { code: 'M4-1', name: '组织架构管理', page: 'sys-dept', module: 'M4' },
  { code: 'M4-2', name: '角色权限管理', page: 'sys-role', module: 'M4' },
  { code: 'M4-3', name: '数据权限', page: 'm4-data-perm', module: 'M4' },
  { code: 'M4-4', name: '操作日志', page: 'sys-oper-log', module: 'M4' },
  { code: 'M4-5', name: '消息通知中心', page: 'm4-notify', module: 'M4' },
  { code: 'M4-6', name: '数据看板', page: 'dash-purchase', module: 'M4' },
  { code: 'M4-7', name: '报表导出', page: 'rpt-purchase', module: 'M4' },
  { code: 'M4-8', name: '系统参数配置', page: 'sys-config', module: 'M4' },
  { code: 'M4-9', name: '单点登录', page: 'login.html', module: 'M4' },
  { code: 'M4-10', name: '数据备份', page: 'm4-backup', module: 'M4' },
];

Object.assign(PAGES, PHASE1_PAGES);
